name: flutter_web_perf
resolution: workspace

environment:
  sdk: ^3.10.0

executables:
  flutter_web_perf:

dependencies:
  args: ^2.4.0
  io: ^1.0.4
  webkit_inspection_protocol: ^1.2.0
  http: ^1.1.0
  shelf: ^1.4.1
  shelf_static: ^1.1.2
  source_maps: ^0.10.12
